sudo: false

addons:
  apt:
    packages:
      - curl
      - make
      - libgc-dev

before_install:
  - git clone --depth=1 git://github.com/nddrylliog/rock.git -b 99x
  - (cd rock && make -s rescue)
  - export PATH=$PATH:$PWD/rock/bin

script:
  - export OOC_LIBS=$PWD
  - rock -v sam.use

notifications:
  webhooks: http://rcmp.pw/freenode/ooc-lang

